### ISSUE TITLE
Can't pass numeric IPv6 as address

### ISSUE THREAD

**Issue by cdleonard** [EnginEken/tcppinglib#4]
The address parameter is very confusing - it seems to accept either an HTTP url or a hostname with associated port.

There does not appear to be any way to pass a non-http ipv6 address because any colon is interpreted as a port marker. Other tools support wrapping ipv6 addresses in square brackets like `[1000:2000::aaaa:bbbb]` but tcppinglib does not.

The whole fact that this tool performs HTTP requests rather than plain TCP is extremely confusing, maybe this should be made explicit or separate?

**Comment by EnginEken** [comment]
Thanks for the feedback @cdleonard . Address parameter calls url_parse function and I am also not satisfied with that function also. But the time I am writing this, that was the best option based on my available time and knowledge. I will change couple things with the address parse function in my spare time. After that change ipv6 address will most probably be supported.

**Comment by EnginEken** [comment]
Hi @cdleonard , 

New release is published with massive changes on library. This issue is also resolved but you need to pass ip addresses as string list to multi_tcpping or async_multi_tcpping functions. You can see the examples for this.

Also ssl socket connection dependet features are removed for now.
